# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teams_pokemon',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teams_trainer',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
