# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_moves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moves',
            name='moves_pokemon',
        ),
        migrations.RemoveField(
            model_name='moves',
            name='moves_type',
        ),
        migrations.DeleteModel(
            name='Moves',
        ),
    ]
