# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0010_team'),
        ('battle', '0006_auto_20181020_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moves_pokemon', models.ManyToManyField(related_name='pokemons_move', to='dashboard.Pokemon')),
                ('moves_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_move', to='dashboard.Types')),
            ],
        ),
    ]
