# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_cpus_cputeam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cputeam',
            name='cpu_teams_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers_cpu_team', to='battle.CPUs'),
        ),
    ]
