# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg', '0002_auto_20181019_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('pokemons_trainer', models.ManyToManyField(related_name='trainers_pokemon', to='log_reg.Trainers')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('types_pokemon', models.ManyToManyField(related_name='pokemons_type', to='dashboard.Pokemon')),
            ],
        ),
    ]
