# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemons_trainer',
        ),
        migrations.RemoveField(
            model_name='types',
            name='types_pokemon',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
