# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_pokemon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='back_sprite',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='front_sprite',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
