# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0003_trainers_trainer_level'),
        ('dashboard', '0006_auto_20181019_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='teams_trainer',
            field=models.ManyToManyField(related_name='teams_pokemon', to='log_reg.Trainers'),
        ),
    ]
