# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_pokemon_teams_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='teams_trainer',
        ),
    ]
