# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_pokemon_teams_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='types',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
