# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0002_auto_20181019_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='trainer_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
