# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0003_trainers_trainer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='character_sprite',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
